### ISSUE TITLE
Waterfall of cifs errors when secondary cifs server is not created

### ISSUE THREAD

**Issue by wfaguy** [oliviermasson/svmtool#10]
[cifs-dr] Impossible to register CIFS server on DR Vserver
[cifs-dr] Configure a temporary IP address on DR Vserver to be able to register your CI
FS server
ERROR: create_update_CIFS_share
[cifs-dr] Check SVM CIFS Server options

If you hit this, there is a waterfall of issues, during update (empty username, empty cifs server names) ... and non of those are caught.

During the update cifs server, we must check if the secondar is already registered or not.  if not keep saying the same error : cifs server not registered.

**Comment by wfaguy** [comment]
Fixed this.
Created a new function that first checks cifs status on primary & secondary and alert accordingly
- if no cifs in primary - just skip
- if no cifs in secondary - alarm that configureDr needs to run to fix this.

Also added this as warning, previously was not really visible.

added the this check in every update_cifs function (shares, users & vserver_dr)

**Comment by oliviermasson** [comment]
Perfect!
