### ISSUE TITLE
Doc download not available

### ISSUE THREAD

**Issue by mschindl** [oliviermasson/svmtool#26]
Hi Olivier,

![image](https://user-images.githubusercontent.com/26382876/50776978-ae4c2480-129a-11e9-8bc6-63107eaa5b91.png)

following link is false: 
 https://github.com/oliviermasson/svmtool/blob/master/SVMTOOL_Manual_v1.0.docx

should be:
 https://github.com/oliviermasson/svmtool/blob/master/SVMTOOL_Manual_v1.1.docx

**Comment by oliviermasson** [comment]
Hi Marc,

Thank you for noticing this.
I just corrected the link.
However, I need to take some time to update this documentation.
Don't forget to use the `get-help svmtool.ps1 -detailed`, which also contains a lot of informations and examples.
