### ISSUE TITLE
Bug lif error on end of update

### ISSUE THREAD

**Issue by willemsem76** [oliviermasson/svmtool#36]
09:18:47.385 INFO  [Svm Dr - Update] [fv603489-dr] ERROR: You need at least one lif on the destination that can communicate with Active Directory. Use ConfigureDR to create one
09:18:47.385 ERROR  [Svm Dr - Update] ERROR: Failed to set all lif up on [fv603489-dr]
09:18:47.713 ERROR  [Svm Dr - Update] Command failed for Workflow 'Svm Dr - Update' with error : An error occurred while parsing EntityName. Line 4, position 10.
09:18:47.713 INFO  [Svm Dr - Update] ***** Workflow Execution Failed *****

I keep getting this error at the end of each update.  Even tough the CIFS join is already done and all other updates seem to run just fine.

**Comment by willemsem76** [comment]
(ps, it's mirko here, at customer).  Meanwhile, I add debug info and there was a typo.  It's not nagging about lif up.  But setting lif down.
09:55:58.482 INFO  [Svm Dr - Update] [fv603489-dr] Create share [geodata$]
09:55:58.779 INFO  [Svm Dr - Update] [fv603489-dr] ERROR: You need at least one lif on the destination that can communicate with Active Directory. Use ConfigureDR to create one
09:55:58.795 ERROR  [Svm Dr - Update] ERROR: [create_update_CIFS_shares_dr] Failed to set all lif down on [fv603489-dr]
09:55:59.123 ERROR  [Svm Dr - Update] Command failed for Workflow 'Svm Dr - Update' with error : An error occurred while parsing EntityName. Line 4, position 10.
09:55:59.123 INFO  [Svm Dr - Update] ***** Workflow Execution Failed *****

**Comment by willemsem76** [comment]
I have added a flag to not throw an error when putting the lifs down at the end of updatedr.  It was a silent fail, but still not necessary.

**Comment by wfaguy** [comment]
I think we fixed this with that extra check if cifs service is already configured

**Comment by oliviermasson** [comment]
merged in release 0.2.6
