### ISSUE TITLE
SnapMirror status "Finalizing" not checked

### ISSUE THREAD

**Issue by c-matzhold** [oliviermasson/svmtool#41]
Hello!

We noticed during migrate command the SnapMirror status "Finalizing" after "Transferring" is not checked by svmtool. This causes errors while breaking the SnapMirror relationships.

I could upload log-file if necessary.

However, great tool!!! 

Best regards,
Christian Matzhold

**Comment by oliviermasson** [comment]
Hi Christian,

Thanks for warning me
Fix in last release
https://github.com/oliviermasson/svmtool/tree/v0.2.7
